---
deployment:
    tasks:
      - export DEPLOYPATH=/home/indegnnk/nyasajob.com
      - export REPOPATH=/home/indegnnk/Nyasajob2026repo
      - export LOGFILE=$REPOPATH/.cpanel/deployment.log
      - mkdir -p $REPOPATH/.cpanel
      - echo "--- Deployment Started: $(date) ---" >> $LOGFILE
      - echo "Commit: $(git rev-parse HEAD)" >> $LOGFILE
      - echo "Author: $(git log -1 --format='%an <%ae>')" >> $LOGFILE
      - echo "Message: $(git log -1 --format='%s')" >> $LOGFILE
      - /bin/rsync -av --delete --exclude='.git' --exclude='.env' --exclude='vendor' --exclude='storage/logs/*' --exclude='storage/framework/cache/*' --exclude='storage/framework/sessions/*' --exclude='storage/framework/views/*' --exclude='public/mix-manifest.json' ./ $DEPLOYPATH/
      - chmod 755 $DEPLOYPATH
      - chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
      - cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev --optimize-autoloader
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force || true
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan storage:link 2>/dev/null || true
      - mkdir -p $DEPLOYPATH/storage/app/public/app/default/ico
      - mkdir -p $DEPLOYPATH/storage/app/public/app/logo
      - cp -n $DEPLOYPATH/public/app/default/* $DEPLOYPATH/storage/app/public/app/default/ 2>/dev/null || true
      - cp -n $DEPLOYPATH/public/app/default/ico/* $DEPLOYPATH/storage/app/public/app/default/ico/ 2>/dev/null || true
      - cp -n $DEPLOYPATH/public/app/logo/* $DEPLOYPATH/storage/app/public/app/logo/ 2>/dev/null || true
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan optimize:clear
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
      - test -f $DEPLOYPATH/public/mix-manifest.json || echo '{ "/dist/public/styles.css": "/dist/public/styles.css", "/dist/public/styles.rtl.css": "/dist/public/styles.rtl.css", "/dist/public/scripts.js": "/dist/public/scripts.js" }' > $DEPLOYPATH/public/mix-manifest.json
      - echo "Status: SUCCESS" >> $LOGFILE
      - echo "Completed: $(date)" >> $LOGFILE
      - echo "" >> $LOGFILE
