deployment:
    tasks:
      - export DEPLOYPATH=/home/indegnnk/nyasajob.com
      - /bin/rsync -av --delete --exclude='.git' --exclude='.env' --exclude='vendor' --exclude='storage/logs/*' --exclude='storage/framework/cache/*' --exclude='storage/framework/sessions/*' --exclude='storage/framework/views/*' --exclude='public/mix-manifest.json' ./ $DEPLOYPATH/
      - chmod 755 $DEPLOYPATH
      - chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
      - cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev --optimize-autoloader
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force || true
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan optimize:clear
      - cd $DEPLOYPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
      - test -f $DEPLOYPATH/public/mix-manifest.json || echo '{ "/dist/public/styles.css": "/dist/public/styles.css", "/dist/public/styles.rtl.css": "/dist/public/styles.rtl.css", "/dist/public/scripts.js": "/dist/public/scripts.js" }' > $DEPLOYPATH/public/mix-manifest.json